---
- name: Install & Configure NGINX
  hosts: manager
  gather_facts: false
  tasks:
   - name: install ngnix on control node 
     yum:
      name: nginx
      state: latest
        
   - name: configure nginx
     template:
       src: /etc/ansible/day3/templ/nginx_template.j2
       dest: /etc/nginx/conf.d/load-balancer.conf
     notify: restart nginx
       
  handlers:
   - name: restart nginx
     service:
      name: nginx
      state: restarted
