---
- name: Install httpd and PHP
  gather_facts: false
  hosts: servers
  become: true
  tasks:
   - name: Install httpd and php
     yum:
      name: 
       - httpd
       - php
       - php-common
       - php-pecl-apcu
       - php-cli
       - php-mysqlnd
      state: installed
